[project]
name = "webtransport-fuzzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aioquic>=1.3.0",
    "boofuzz>=0.4.2",
    "nest-asyncio>=1.6.0",
]
